ruby "2.4.2"
source 'https://rubygems.org'

gem 'sinatra'
gem 'rerun'

gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 's3'
gem 'twilio-ruby'
gem 'mini_magick'

gem 'haml'
gem 'sass'
gem 'kramdown'

gem 'rdoc'
gem 'rake'
gem 'dotenv'

gem 'better_errors'
gem 'binding_of_caller'
gem 'pry'
gem 'pry-byebug'
gem 'sinatra-flash'
gem 'aws-sdk', '~> 2'
gem 'dimensions'
gem 'streamio-ffmpeg'